spring:
  datasource:
    username:
    password:
    url:
    driver-class-name:
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
      max-file-size:
      max-request-size:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    stack:
      auto:
    bucket:
      name:


application:
  security:
    jwt:
      secret:
        secret-key:
        refresh-secret-key:
      access-token:
        expiration-time:
      refresh-token:
        expiration-time:

whatsapp:
  api-url:
  api-key:
  source-name:
  source-number:
  template-id:

